### ISSUE TITLE
Locks collection field

### ISSUE THREAD

**Issue by bigdork** [bearlikelion/popularplex#2]
Script locks the collection field, causing error on re-run if the same series is still popular

**Comment by bearlikelion** [comment]
Can you provide the error or exception you are seeing when re-running the script?
I frequently run it one after another during development, the clear_collections() function should empty out the configured Movie and TV collections before adding media back without locking the field.

**Comment by bigdork** [comment]
Actually, I don't think it's the lock that's causing it.

The script appears to be trigging a metadata refresh on the items post-add or remove.
NBD for movies, the new agent is very quick, but large TV shows on the (ie: Supernatural, The Walking Dead, Spongebob) take time to complete with the slower agent.

- I purged the collections, then ran the script (completed OK). 
- Waited for metadata refresh to complete on the TV items.
- Ran script again (which will remove and re-add the same items)
- Upon remove, the TV items enter the metadata refresh "phase" again, and the script fails when attempting to re-add them with a Plex timeout
- Note, Movie collection was created fine, metadata refresh after removal is fast enough to complete before the re-add begins. Problem lies with attempting to re-add TV items that were just removed.

**Is the metadata refresh necessary?**

$ python3 popular_plex.py
Logging in using token
Getting popular media
Clear Collections
    Removing Garfield in Disguise from Popular Movies
    Removing Halloweentown from Popular Movies
    Removing Halloweentown II: Kalabar's Revenge from Popular Movies
    Removing Halloweentown High from Popular Movies
    Removing Sisters from Popular Movies
    Removing Sing from Popular Movies
    Removing War for the Planet of the Apes from Popular Movies
    Removing Z from Popular Movies
    Removing Alone from Popular Movies
    Removing Death of Me from Popular Movies
    Removing Friends from Popular TV Shows
    Removing SpongeBob SquarePants from Popular TV Shows
    Removing Supernatural from Popular TV Shows
    Removing The Walking Dead from Popular TV Shows
    Removing Penn & Teller: Fool Us from Popular TV Shows
    Removing Bob's Burgers from Popular TV Shows
    Removing Yellowstone (2018) from Popular TV Shows
Traceback (most recent call last):
  File "/home/pg/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/pg/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 272, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pg/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/pg/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/pg/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/pg/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/home/pg/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/pg/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/pg/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='plex.domain.cc', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "popular_plex.py", line 88, in <module>
    clear_collections()
  File "popular_plex.py", line 47, in clear_collections
    show.removeCollection(config['Collections']['movies'])
  File "/home/pg/.local/lib/python3.6/site-packages/plexapi/base.py", line 393, in removeCollection
    self._edit_tags('collection', collections, remove=True)
  File "/home/pg/.local/lib/python3.6/site-packages/plexapi/base.py", line 381, in _edit_tags
    self.refresh()
  File "/home/pg/.local/lib/python3.6/site-packages/plexapi/base.py", line 427, in refresh
    self._server.query(key, method=self._server._session.put)
  File "/home/pg/.local/lib/python3.6/site-packages/plexapi/server.py", line 440, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/home/pg/.local/lib/python3.6/site-packages/requests/sessions.py", line 590, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/home/pg/.local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pg/.local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/pg/.local/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='plex.domain.com', port=443): Read timed out. (read timeout=30)

**Comment by bigdork** [comment]
Actually, I don't think it's the lock that's causing it.

The script appears to be trigging a metadata refresh on the items post-add or remove.
NBD for movies, the new agent is very quick, but large TV shows on the (ie: Supernatural, The Walking Dead, Spongebob) take time to complete with the slower agent.

- I purged the collections, then ran the script (completed OK). 
- Waited for metadata refresh to complete on the TV items.
- Ran script again (which will remove and re-add the same items)
- Upon remove, the TV items enter the metadata refresh "phase" again, and the script fails when attempting to re-add them with a Plex timeout
- Note, Movie collection was created fine, metadata refresh after removal is fast enough to complete before the re-add begins. Problem lies with attempting to re-add TV items that were just removed and still updating their metadata.

**Is the metadata refresh necessary?**

**Comment by meisnate12** [comment]
All this script does is call the plexapi method called removeCollection. It doesn't actually tell anything to refresh. So either the plexapi is refreshing on removal or plex itself refreshes on removal. I would wager it's the later, that plex itself is causing the refresh. If it is on plex there may be a plex setting that when changed may fix this issue.

**Comment by bigdork** [comment]
You may be right - I've disabled " Run a partial scan when changes are detected" but noticed there was an update.
After update, the script won't run. Thoughts?

Output below, and a snippet from the [Plex] section of my config.

```
$ git pull https://github.com/bearlikelion/popularplex.git
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 8 (delta 5), reused 7 (delta 4), pack-reused 0
Unpacking objects: 100% (8/8), done.
From https://github.com/bearlikelion/popularplex
 * branch            HEAD       -> FETCH_HEAD
Updating a950604..654b893
Fast-forward
 README.md       | 8 ++++++++
 popular_plex.py | 4 +++-
 2 files changed, 11 insertions(+), 1 deletion(-)

$ python3 popular_plex.py
Traceback (most recent call last):
  File "popular_plex.py", line 76, in <module>
    if (config['Plex']['url'] != '' and config['Plex']['token'] != ''):
  File "/usr/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'Plex'
```

```
$ cat config.ini
[Plex]
url = https://plex.domain.cc
token = _VxxxxxxxxxxxxM
username =
password =
server =
```

**Comment by bigdork** [comment]
To bypass the new crashing, I replaced line 69
`    config.read(os.path.dirname(__file__) + os.path.sep + 'config.ini')
`
with the following from a prior version:
`    config.read('config.ini')
`
Script runs now. 

I can confirm removing the "Run a partial scan when changes are detected" setting in Plex prevents the crashing due to metadata refresh!

**_(I'm not github-savvy, should I close this issue and open a new one for the config.read problem?)_**

**Comment by bearlikelion** [comment]
Yes, ideally we would close this issue and open a new one for the config.ini issue, but I'm curious what your output for:

```
os.path.dirname(__file__) + os.path.sep + 'config.ini'
```

This change was made so when the script runs outside from its directory it still uses the local config.ini file instead of looking for it in the current directory (like C:\Windows\System32)

You can reproduce by calling the python path from outside the git repo directory

**Comment by bigdork** [comment]
With line 69 as
`config.read(os.path.dirname(__file__) + os.path.sep + 'config.ini')`
the script runs if executed from outside the script directory, but not from within the script directory.

The reverse is true with line 69 as
`config.read('config.ini')`
where the script fails to execute from outside the script directory, but runs properly if executed from within the script directory. 

Since I'm still just testing this out, I'd not yet moved it to my scripts path and have only been executing manually from my home directory. Now that I understand this behavior I can avoid the problem.

**Comment by bearlikelion** [comment]
The script has now been updated to look for a local config.ini, if not use the script_path to find one
https://github.com/bearlikelion/popularplex/commit/9d5276f9aa3b2e4b8c167bfa00a5d066e7446948
