### ISSUE TITLE
Incorrect items collected

### ISSUE THREAD

**Issue by bigdork** [bearlikelion/popularplex#3]
Man, had such high hopes. I've been updating a manual "Popular" collection every month.
However, although the proper items were collected for TV shows, the Movies collection was way off.
- Incorrect movies added
- TV shows added?
- Music album added?

Attached are screenshots of config, execution, collections, and the Tautulli "Popular Movies"list.

<img width="333" alt="script-config" src="https://user-images.githubusercontent.com/58086116/96818508-9900a580-13ef-11eb-9a8c-970314c045df.png">
<img width="421" alt="script-execute" src="https://user-images.githubusercontent.com/58086116/96818504-97cf7880-13ef-11eb-9fae-5cfa768901f5.png">
<img width="367" alt="plex-collections" src="https://user-images.githubusercontent.com/58086116/96818506-98680f00-13ef-11eb-9dd2-28c702f8a74f.png">
<img width="804" alt="plex-popularmovies" src="https://user-images.githubusercontent.com/58086116/96818489-930ac480-13ef-11eb-94b7-4a9970c92672.png">
<img width="516" alt="tautulli-movies1" src="https://user-images.githubusercontent.com/58086116/96818509-9900a580-13ef-11eb-843f-897e4c0fa3fb.png">
<img width="511" alt="tautulli-movies2" src="https://user-images.githubusercontent.com/58086116/96818500-97cf7880-13ef-11eb-96e7-6ff7b2f60527.png">

**Comment by bearlikelion** [comment]
Thank you for the detailed issue!

I have made some changes to the script based on your issues, the major one is that the lookup I used to add media to the collections was a generic search returning the first result. This would cause issues if there were multiple media with the same title (Example: Z - 1969 and Z - 2019).

The latest change now adds media based on their unique Plex ID, so there should be no mistakes

https://github.com/bearlikelion/popularplex/commit/a95060471f88dbb43eec361b40a31349f12a5e16#diff-0fc385faafd64e424c48e432c0b92c27505da72f48165ff07eb733e251e1c2e7L57

Please pull the latest changes and try to run the script again.

**Comment by bigdork** [comment]
That worked, thank you!
