### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Piblokto** [bearlikelion/popularplex#4]
Import error for configparser on Ubuntu. Tried installing configparser through pip yet to no avail.
What version was this Python script written for, and why isn't it in the requirements.txt?

**Comment by bearlikelion** [comment]
What version of Python are you running?
The script is designed for Python3, where [configparser ](https://docs.python.org/3/library/configparser.html) is included in Libs.
I will update the README to reflect python3 as a requirement.
