### ISSUE TITLE
Docker version

### ISSUE THREAD

**Issue by Djeloan** [bearlikelion/popularplex#6]
Could we get a docker installation version, so updating and maintaining is much simpler?

**Comment by bearlikelion** [comment]
Of course, while I'm familiar with docker I haven't really created my own dockerfiles yet, I'll look into it this week.

Thank you for the suggestions 👍

**Comment by bearlikelion** [comment]
I created and tested a Dockerfile, and updated the README with instructions on building the container.
This was a fun one, thanks for the issue 👍
